# Usar imagem oficial Python
FROM python:3.11-slim

# Setar diretório de trabalho
WORKDIR /app

# Copiar os arquivos necessários
COPY bot_telegram/ ./bot_telegram
COPY chat/ ./chat
COPY rag_juridico/ ./rag_juridico
COPY dataset/ ./dataset
COPY docker/requirements.txt ./requirements.txt

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt


# COPY .env .env

# Comando para iniciar o bot
CMD ["python", "bot_telegram/bot.py"]
